export interface IUser {
    _id?: string,
    username: string,
    name: string,
    surname: string,
    email: string,
    password: string,
    profilePicture?: string,
    coverPicture?: string,
    description?: string,
    city?: string,
    university?:string,
    age?: string,
    followers?: [string],
    following?: [string],
    isAdmin?: boolean,
    createdAt?: Date,
    updatedAt?: Date,
}